config/routes.rb
Rails.application.routes.draw do
  root to: "regions#index"
  resources :regions do
    resources :mechanisms
  end

  get 'bootregions', to: 'regions#bootRegions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulldozer.rb
class Bulldozer < Mechanism

end

app/models/evacuator.rb
class Evacuator < Mechanism
end

app/models/excavator.rb
class Excavator < Mechanism

end

app/models/mechanism.rb
class Mechanism < ApplicationRecord
  belongs_to :Region


end

app/models/region.rb
class Region < ApplicationRecord
  has_many :mechanisms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mechanisms_controller.rb
class MechanismsController < ApplicationController
  before_action :set_mechanism, only: [:show, :edit, :update, :destroy]

  # GET /mechanisms
  # GET /mechanisms.json
  def index
    @mechanisms = Mechanism.all
    e = Excavator.new
    @note = Mechanism.descendants
  end

  # GET /mechanisms/1
  # GET /mechanisms/1.json
  def show
  end

  # GET /mechanisms/new
  def new
    @region = Region.find(params[:region_id])
    @mechanism = Mechanism.new
    e = Mechanism.new
    @typeMechanism = Mechanism.subclasses
    @note = @typeMechanism
  end

  # GET /mechanisms/1/edit
  def edit
  end

  # POST /mechanisms
  # POST /mechanisms.json
  def create
    @region = Region.find(params[:region_id])
    @mechanism = Mechanism.new(mechanism_params)

    respond_to do |format|
      if @mechanism.save
        format.html { redirect_to region_mechanism_path(@mechanism.Region, @mechanism.id), notice: 'Mechanism was successfully created.' }
        format.json { render :show, status: :created, location:  @mechanism }
      else
        format.html { render :new }
        format.json { render json: @mechanism.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mechanisms/1
  # PATCH/PUT /mechanisms/1.json
  def update
    respond_to do |format|
      if @mechanism.update(mechanism_params)
        format.html { redirect_to [@region, @mechanism], notice: 'Mechanism was successfully updated.' }
        format.json { render :show, status: :ok, location: [@region, @mechanism] }
      else
        format.html { render :edit }
        format.json { render json: @mechanism.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mechanisms/1
  # DELETE /mechanisms/1.json
  def destroy
    @mechanism.destroy
    respond_to do |format|
      format.html { redirect_to region_mechanisms_url, notice: 'Mechanism was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mechanism
      @region = Region.find(params[:region_id])
      @mechanism = Mechanism.find(params[:id])
      e = Excavator.new
      @typeMechanism = ObjectSpace.each_object(Class).to_a
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mechanism_params
      params.require(:mechanism).permit(:name, :rating, :image, :price, :Region_id, :type)
    end
end

app/controllers/regions_controller.rb
require 'json'

class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #загрузка регионов из о json в бд
  def bootRegions
    #TODO Добавть что могут делать только админы, когда будут пользователи

    #Получаем хеш регионов с номерами регионов
    data = File.read('lib/jsondb/russia.subjects.json', encoding: 'utf-8')
    @hash_regions = JSON.parse(data)

    # Вылавливаем данные из хеша
    @out_regions = {}
    @hash_regions['data'].each do |hash|
      @out_regions[hash['regioncode']] = hash['name']
    end
    #Сортируем по возрастанию номер региона
    @out_regions = @out_regions.sort_by { |regioncode,name| regioncode}

    if (!Region.exists?(1))
      @out_regions.each do |key, name_region|
        Region.create(name: name_region)
      end
      @boot_message = "Данные в базу загружены"
    else
      @boot_message = 'Данные не загружены, в базе уже что-то есть, очистить бд: rake db:drop db:create db:migrate'
    end



  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_region
    @region = Region.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def region_params
    params.require(:region).permit(:name, :type)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mechanisms_helper.rb
module MechanismsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technique</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-expand-sm navbar-light bg-faded">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Brand -->
        <%= link_to 'Регионы', regions_path, class: "navbar-brand" %>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="nav-content">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Техника', region_mechanisms_path(42), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link 2</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="Preview">
                <a class="dropdown-item" href="#">Dropdown Link 1</a>
                <a class="dropdown-item" href="#">Dropdown Link 2</a>
                <a class="dropdown-item" href="#">Dropdown Link 3</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
      <% end %>
      <p id="my_notice"><%=  @note if !@note.nil? %></p>

      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/mechanisms/_form.html.erb
<%= form_for(  @mechanism,  url: {action: "create"}  ) do |f| %>
  <% if @mechanism.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mechanism.errors.count, "error") %> prohibited this mechanism from being saved:</h2>

      <ul>
      <% @mechanism.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

    <div class="field">
      <%= f.label :type %>
      <%= f.select(:type) do %>
          <!--TODO найти как можно извлечь дочернии классы-->
          <% [['Экскаватор', 'Excavator'], ['Бульдозер', 'Bulldozer'],['Эвакуатор', 'Evacuator']].each do |c| -%>
              <%= content_tag(:option, c.first, value: c.last) %>
          <% end %>
      <% end %>
    </div>

  <div class="field">
    <%= f.hidden_field :Region_id, value: @region.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mechanisms/edit.html.erb
<h1>Editing Mechanism</h1>

<%= render 'form', mechanism: @mechanism %>

<%= link_to 'Show', edit_region_mechanism_path(@mechanism.Region, @mechanism) %> |
<%= link_to 'Back', region_mechanisms_path %>

app/views/mechanisms/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Mechanisms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Image</th>
      <th>Price</th>
      <th>Region</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mechanisms.each do |mechanism| %>
      <tr>
        <td><%= mechanism.name %></td>
        <td><%= mechanism.rating %></td>
        <td><%= mechanism.image %></td>
        <td><%= mechanism.price %></td>
        <td><%= mechanism.Region %></td>
        <td><%= mechanism.type %></td>
        <td><%= link_to 'Show', region_mechanism_path(mechanism.Region, mechanism.id) %></td>
        <td><%= link_to 'Edit', edit_region_mechanism_path(mechanism.Region, mechanism.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mechanism', new_region_mechanism_path %>

app/views/mechanisms/new.html.erb
<h1>New Mechanism</h1>

<%= render 'form' %>


<%= link_to 'Back', region_mechanisms_path %>

app/views/mechanisms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id</strong>
  <%= @mechanism.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @mechanism.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @mechanism.rating %>
</p>

<p>
  <strong>Image:</strong>
  <%= @mechanism.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @mechanism.price %>
</p>

<p>
  <strong>Region:</strong>
  <%= @mechanism.Region %>
</p>

<%= link_to 'Edit', edit_region_mechanism_path([@region, @mechanism]) %> |
<%= link_to 'Back', region_mechanisms_path %>

app/views/regions/_form.html.erb
<%= form_for(region) do |f| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions ">
    <%= f.submit 'Отправить', class: "btn btn-primary"%>
  </div>
<% end %>

app/views/regions/bootRegions.html.erb
<h1>Загрузка регионов</h1>
<div class="flash">
  <h3><%= @boot_message %></h3>
</div>
<br>

<div class="raw"><small><%= @out_regions %></small></div>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Техника', region_mechanisms_path(@region) %>
<%= link_to 'Back', regions_path %>